### ISSUE TITLE
TypeError: DeepLake.__init__() got an unexpected keyword argument 'read_only'

### ISSUE THREAD

**Issue by masapasa** [peterw/Chat-with-Github-Repo#1]
2023-04-25 18:37:50.156 Uncaught app exception
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "Documents/Chat-with-Github-Repo/chat.py", line 38, in <module>
    db = DeepLake(dataset_path=active_loop_data_set_path, read_only=True, embedding_function=embeddings)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeepLake.__init__() got an unexpected keyword argument 'read_only'
2023-04-25 18:37:51.843 Uncaught app exception
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "Documents/Chat-with-Github-Repo/chat.py", line 38, in <module>
    db = DeepLake(dataset_path=active_loop_data_set_path, read_only=True, embedding_function=embeddings)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeepLake.__init__() got an unexpected keyword argument 'read_only'
2023-04-25 18:37:54.475 Uncaught app exception
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "Documents/Chat-with-Github-Repo/chat.py", line 38, in <module>
    db = DeepLake(dataset_path=active_loop_data_set_path, read_only=True, embedding_function=embeddings)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeepLake.__init__() got an unexpected keyword argument 'read_only'
2023-04-25 18:37:58.851 Uncaught app exception
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "Documents/Chat-with-Github-Repo/chat.py", line 38, in <module>
    db = DeepLake(dataset_path=active_loop_data_set_path, read_only=True, embedding_function=embeddings)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeepLake.__init__() got an unexpected keyword argument 'read_only'
2023-04-25 18:38:08.388 Uncaught app exception
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "Documents/Chat-with-Github-Repo/chat.py", line 38, in <module>
    db = DeepLake(dataset_path=active_loop_data_set_path, read_only=True, embedding_function=embeddings)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeepLake.__init__() got an unexpected keyword argument 'read_only'
2023-04-25 18:47:02.915 Uncaught app exception
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "Documents/Chat-with-Github-Repo/chat.py", line 38, in <module>
    db = DeepLake(dataset_path=active_loop_data_set_path, read_only=True, embedding_function=embeddings)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeepLake.__init__() got an unexpected keyword argument 'read_only'
2023-04-25 18:47:02.918 Uncaught app exception
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "Documents/Chat-with-Github-Repo/chat.py", line 38, in <module>
    db = DeepLake(dataset_path=active_loop_data_set_path, read_only=True, embedding_function=embeddings)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeepLake.__init__() got an unexpected keyword argument 'read_only'
2023-04-25 18:47:03.473 Uncaught app exception
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "Documents/Chat-with-Github-Repo/chat.py", line 38, in <module>
    db = DeepLake(dataset_path=active_loop_data_set_path, read_only=True, embedding_function=embeddings)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeepLake.__init__() got an unexpected keyword argument 'read_only'
2023-04-25 18:47:03.820 Uncaught app exception
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "Documents/Chat-with-Github-Repo/chat.py", line 38, in <module>
    db = DeepLake(dataset_path=active_loop_data_set_path, read_only=True, embedding_function=embeddings)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeepLake.__init__() got an unexpected keyword argument 'read_only'
2023-04-25 18:47:03.959 Uncaught app exception
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "Documents/Chat-with-Github-Repo/chat.py", line 38, in <module>
    db = DeepLake(dataset_path=active_loop_data_set_path, read_only=True, embedding_function=embeddings)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeepLake.__init__() got an unexpected keyword argument 'read_only'

**Comment by davidbuniat** [comment]
@masapasa can you share the output of `pip3 freeze`?
