### ISSUE TITLE
deeplake.util.exceptions.TensorDoesNotExistError: "Tensor 'id' does not exist."

### ISSUE THREAD

**Issue by plintner** [peterw/Chat-with-Github-Repo#22]
I'm getting an error during processing. Any suggestions? 

> Deep Lake Dataset in hub://adrenalineuser/repo-chat already exists, loading from the storage
Traceback (most recent call last):
  File "src/main.py", line 110, in <module>
    main()
  File "src/main.py", line 104, in main
    process_repo(args)
  File "src/main.py", line 33, in process_repo
    process(
  File "/home/username/DevelopmentWSL/Chat-with-Github-Repo/src/utils/process.py", line 105, in process
    db.add_documents(texts)
  File "/home/username/.local/lib/python3.8/site-packages/langchain/vectorstores/base.py", line 72, in add_documents
    return self.add_texts(texts, metadatas, **kwargs)
  File "/home/username/.local/lib/python3.8/site-packages/langchain/vectorstores/deeplake.py", line 184, in add_texts
    return self.vectorstore.add(
  File "/home/username/.local/lib/python3.8/site-packages/deeplake/core/vectorstore/deeplake_vectorstore.py", line 230, in add
    processed_tensors, id = dataset_utils.preprocess_tensors(
  File "/home/username/.local/lib/python3.8/site-packages/deeplake/core/vectorstore/vector_search/dataset/dataset.py", line 254, in preprocess_tensors
    if dataset and dataset[tensor_name].htype == "image":
  File "/home/username/.local/lib/python3.8/site-packages/deeplake/core/dataset/dataset.py", line 506, in __getitem__
    raise TensorDoesNotExistError(item)
deeplake.util.exceptions.TensorDoesNotExistError: "Tensor 'id' does not exist."

**Comment by AsmaaMHadir** [comment]
I am getting the same error running the `ConversationalRetrievalChain.from_llm` object. I'm researching a potential workaround/solution
