### ISSUE TITLE
ValueError when processing repo:: `texts` parameter shouldn't be empty.

### ISSUE THREAD

**Issue by chrisammon3000** [peterw/Chat-with-Github-Repo#26]
## Description
Followed the README instructions for installation, encountered a ValueError when processing repositories:
```bash
(.venv) ➜  Chat-with-Github-Repo (main) python3 src/main.py process --repo-url https://github.com/chrisammon3000/aws-json-dataset               ✭
Your Deep Lake dataset has been successfully created!
This dataset can be visualized in Jupyter Notebook by ds.visualize() or at https://app.activeloop.ai/chrisammon3000/aws-json-dataset
hub://chrisammon3000/aws-json-dataset loaded successfully.
fatal: destination path 'repos' already exists and is not an empty directory.
Using embedding function is deprecated and will be removed in the future. Please use embedding instead.
Deep Lake Dataset in hub://chrisammon3000/aws-json-dataset already exists, loading from the storage
Traceback (most recent call last):
  File "/Users/ammon/Projects/chrisammon3000/experiments/Chat-with-Github-Repo/src/main.py", line 110, in <module>
    main()
  File "/Users/ammon/Projects/chrisammon3000/experiments/Chat-with-Github-Repo/src/main.py", line 104, in main
    process_repo(args)
  File "/Users/ammon/Projects/chrisammon3000/experiments/Chat-with-Github-Repo/src/main.py", line 33, in process_repo
    process(
  File "/Users/ammon/Projects/chrisammon3000/experiments/Chat-with-Github-Repo/src/utils/process.py", line 105, in process
    db.add_documents(texts)
  File "/Users/ammon/Projects/chrisammon3000/experiments/Chat-with-Github-Repo/.venv/lib/python3.11/site-packages/langchain/vectorstores/base.py", line 101, in add_documents
    return self.add_texts(texts, metadatas, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ammon/Projects/chrisammon3000/experiments/Chat-with-Github-Repo/.venv/lib/python3.11/site-packages/langchain/vectorstores/deeplake.py", line 217, in add_texts
    raise ValueError("`texts` parameter shouldn't be empty.")
ValueError: `texts` parameter shouldn't be empty.
```

**Comment by hankerbiao** [comment]
Bro，is this problem sloved？

**Comment by whilelie** [comment]
I also have this error

**Comment by Jaswin** [comment]
@chrisammon3000 - Were you able to resolve it ?

**Comment by Jaswin** [comment]
spec.match_file(file_path) matches the absolute path, while it should use a relative path from root_dir.

In process.py, Update this part in load_docs():

if spec and spec.match_file(file_path):

to 

if spec and spec.match_file(os.path.relpath(file_path, root_dir)):
